_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSS,",
    offsets = "0,",
    addresses = "0x164b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSS,MOVSS,",
    offsets = "0,0,",
    addresses = "0x1668,0x1682,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSS,",
    offsets = "0,",
    addresses = "0x1634,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LLLLLLLLLLLS",
    opcodes = "MOV,CMP,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,ADD,",
    offsets = "-12,-20,-12,-48,-16,-12,-40,-12,-32,-12,-32,-12,",
    addresses = "0x168a,0x168d,0x1619,0x162a,0x1631,0x1639,0x1644,0x1656,0x1661,0x166c,0x1677,0x1686,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 36,
    accessed_memory_overlap = 28,
    span = 40,
    head = 0,
    unroll_factor = 1,
  },
}
