_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VMOVSS,",
    offsets = "0,0,",
    addresses = "0x401691,0x40169d,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "VGETMANTSS,VMOVSS,VGETMANTSS,VMOVSS,",
    offsets = "0,0,0,0,",
    addresses = "0x40167f,0x40168b,0x4016e8,0x40170d,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 12,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VMOVSS,",
    offsets = "0,0,",
    addresses = "0x4016f4,0x401700,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LSLS",
    opcodes = "VADDSS,VMOVSS,VADDSS,VMOVSS,",
    offsets = "0,0,0,0,",
    addresses = "0x4016d9,0x4016df,0x40173b,0x401741,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 12,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
