_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VMOVSS,",
    offsets = "0,0,",
    addresses = "0x401607,0x40160d,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "VMOVSS,VMOVSS,VMOVSS,VMOVSS,",
    offsets = "0,0,0,0,",
    addresses = "0x4015ed,0x4015fa,0x40165c,0x401689,",
    stride_status = "Success",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 12,
    span = 4,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VMOVSS,",
    offsets = "0,0,",
    addresses = "0x401670,0x401676,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LSLS",
    opcodes = "VADDSS,VMOVSS,VADDSS,VMOVSS,",
    offsets = "0,0,0,0,",
    addresses = "0x401650,0x401656,0x4016b7,0x4016be,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 12,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
