_group = {
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOVSS,",
    offsets = "0,",
    addresses = "0x129f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSS,",
    offsets = "7646,",
    addresses = "0x128e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 6,
    pattern = "LLLLLS",
    opcodes = "MOV,CMP,MOV,MOV,MOV,ADD,",
    offsets = "-32,-36,-28,-48,-32,-32,",
    addresses = "0x12a8,0x12ab,0x1272,0x1287,0x129a,0x12a4,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 28,
    accessed_memory_nooverlap = 20,
    accessed_memory_overlap = 8,
    span = 24,
    head = 0,
    unroll_factor = 1,
  },
}
