_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVUPS,",
    offsets = "0,",
    addresses = "0x1d25,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVUPS,",
    offsets = "0,",
    addresses = "0x1d3a,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVUPS,",
    offsets = "0,",
    addresses = "0x1d10,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "VFMADD213PS,VMOVAPS,",
    offsets = "0,0,",
    addresses = "0x1d17,0x1d1e,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 64,
    span = 64,
    head = 64,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "VFMADD213PS,VMOVUPS,",
    offsets = "0,0,",
    addresses = "0x1d2c,0x1d33,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 64,
    span = 64,
    head = 64,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "VFMADD213PS,VMOVUPS,",
    offsets = "0,0,",
    addresses = "0x1d42,0x1d49,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 64,
    span = 64,
    head = 64,
    unroll_factor = 1,
  },
}
