_group = {
  {
    group_size = 5,
    pattern = "SSLLL",
    opcodes = "MOV,MOV,VMULSS,VMULSS,VMULSS,",
    offsets = "12,12,12,12,12,",
    addresses = "0x151d,0x152c,0x1541,0x156b,0x1595,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 20,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 16,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 6,
    pattern = "SSSSSS",
    opcodes = "VMOVSS,VMOVSS,VMOVSS,VMOVSS,VMOVSS,VMOVSS,",
    offsets = "-24,-20,-16,-12,-8,-4,",
    addresses = "0x1547,0x155d,0x1571,0x1587,0x159b,0x15b1,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 6,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMULSS,VMULSS,VMULSS,",
    offsets = "3011,2969,2927,",
    addresses = "0x1555,0x157f,0x15a9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 12,
    accessed_memory_overlap = 0,
    span = 88,
    head = 0,
    unroll_factor = 3,
  },
}
