_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSS,",
    offsets = "0,",
    addresses = "0x16e8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSS,MOVSS,",
    offsets = "0,0,",
    addresses = "0x1705,0x171f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSS,",
    offsets = "0,",
    addresses = "0x16d1,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LLLLLLLLLLLS",
    opcodes = "MOV,CMP,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,ADD,",
    offsets = "-12,-20,-12,-48,-16,-12,-40,-12,-32,-12,-32,-12,",
    addresses = "0x1727,0x172a,0x16b6,0x16c7,0x16ce,0x16d6,0x16e1,0x16f3,0x16fe,0x1709,0x1714,0x1723,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 36,
    accessed_memory_overlap = 28,
    span = 40,
    head = 0,
    unroll_factor = 1,
  },
}
